### PR TITLE
Use `static` to define CheckStackTrace on non-GNU

### LINKED ISSUE #421: windows: test failed - stacktrace
failing on AppVeyor

https://ci.appveyor.com/project/ukai/benchmark/builds/21821089/job/rdqmviqc86ghuhq8
```
Test project C:/projects/benchmark/_build_vs-14-2015-sdk-8-1_Debug
      Start 1: demangle
  1/6 Test #1: demangle .........................   Passed    0.03 sec
      Start 2: logging
  2/6 Test #2: logging ..........................   Passed    0.37 sec
      Start 3: signalhandler
  3/6 Test #3: signalhandler ....................   Passed    0.01 sec
      Start 4: stacktrace
  4/6 Test #4: stacktrace .......................***Timeout  30.00 sec
  Obtained 10 stack frames.
  Backtrace 0: expected: 00007FF7E2D94500..00007FF7E2D94600  actual: 00007FF7E2D9459F ... OK
  Backtrace 1: expected: 00007FF7E2D94840..00007FF7E2D94940  actual: 00007FF7E2D948CB ... OK
  Backtrace 2: expected: 00007FF7E2D948E0..00007FF7E2D949E0  actual: 00007FF7E2D9496F ... OK
  Backtrace 3: expected: 00007FF7E2D94990..00007FF7E2D94A90  actual: 00007FF7E2D94A1F ... OK
  Backtrace 4: expected: 00007FF7E2D94A40..00007FF7E2D94B40  actual: 00007FF7E2D94ACF ... OK
  Backtrace 5: expected: 00007FF7E2D91E38..00007FF7E2D91F38  actual: 00007FF7E2D944E9 ... F0123 05:10:27.501575  2840 stacktrace_unittest.cc:109] Check failed: ret_addr <= range.end (00007FF7E2D944E9 vs. 00007FF7E2D91F38) 
  *** Check failure stack trace: ***
      @   00007FF7E2D9712B  google::LogMessage::Fail
      @   00007FF7E2D97031  google::LogMessage::SendToLog
      @   00007FF7E2D96817  google::LogMessage::Flush
      @   00007FF7E2D98421  google::LogMessageFatal::~LogMessageFatal
      @   00007FF7E2D94443  CheckRetAddrIsInFunction
      @   00007FF7E2D947EE  CheckStackTraceLeaf
      @   00007FF7E2D948CB  CheckStackTrace4
      @   00007FF7E2D9496F  CheckStackTrace3
      @   00007FF7E2D94A1F  CheckStackTrace2
      @   00007FF7E2D94ACF  CheckStackTrace1
      @   00007FF7E2D944E9  CheckStackTrace
      @   00007FF7E2D94B36  main
      @   00007FF7E2DB4C24  invoke_main
      @   00007FF7E2DB4AC7  __scrt_common_main_seh
      @   00007FF7E2DB498E  __scrt_common_main
      @   00007FF7E2DB4C49  mainCRTStartup
      @   00007FFB4EF28364  BaseThreadInitThunk
      @   00007FFB4F36E851  RtlUserThreadStart
  
      Start 5: stl_logging
  5/6 Test #5: stl_logging ......................   Passed    0.01 sec
      Start 6: symbolize
  6/6 Test #6: symbolize ........................   Passed    0.02 sec
  
  83% tests passed, 1 tests failed out of 6
  
  Total Test time (real) =  30.45 sec
  
  The following tests FAILED:
  	  4 - stacktrace (Timeout)
  Errors while running CTest
```

### PR DESCRIPTION
**Pull request by shinh**
An attempt to fix #421. I don't know if this work.

### CODE REVIEW

**Comment by shinh** [comment]
It worked. I'm not 100% sure, but I think the compiler returns the address of PLT-like thing for non-static function on Windows.

**Comment by shinh** [comment]
Pinging @andschwa . I guess you may know a better solution :)

**Comment by shinh** [comment]
Added a link to #421 to see if this actually makes appveyor green.

**Comment by andschwa** [comment]
@shinh This looks good to me 🎉 (I'm no Windows expert, I just got an impl working based on docs 😆)

**Pull request merged**
