### PR TITLE
OverrideLogCleanerFilePathPrefix to override the files the log cleane…

### PR DESCRIPTION
**Pull request by mturnock**
…r removes

### CODE REVIEW

**Comment by mturnock** [comment]
My requirement was that I delete old log files, regardless of log level.
I was looking to achieve something similar to https://github.com/google/glog/pull/1062, but I don't think that approach is very easy.  So instead I extended the interface to override the files the log cleaner cleans, giving flexibility to users of the log cleaner on what they want cleaning.

**Comment by mturnock** [comment]
> Thanks for the PR!
> 
> However, I'm not sure I understand why we need to extended the public API instead of fixing the underlying issue?

I don't think I have come up with a better alternative.  I'm open to suggestions.

Some possible thoughts:
1. Make next_cleanup_time_ a map, 1 entry per base_filename.  Pro: no change to interface.  Con: only deletes old log of a particular level when a new log line of that level is made.
2. Add a registration system to log cleaner from each LogDestination.  Con: seemed a bit gnarly.

**Comment by mturnock** [comment]
The suggestion from https://github.com/google/glog/pull/1062 is that we can fix IsLogFromCurrentProject, but I don't know if that is possible in general because the user can set any log name style they want with SetLogDestination

**Comment by sergiud** [comment]
I would prefer no additional methods if possible since using log cleaner will become less intuitive than it already is.

While the log destination can be different the suffix is always the same. Combined with the observation that log severities are known at compile time determining candidates for deletion should be doable.

**Comment by mturnock** [comment]
Consider:

  SetLogDestination(GLOG_INFO, "/path/to/logs/applog-carrots-");
  SetLogDestination(GLOG_WARNING, "/path/to/logs/applog-peas-");
  SetLogDestination(GLOG_ERROR, "/path/to/logs/applog-corn-");
  SetLogFilenameExtension(".log");
  EnableLogCleaner(std::chrono::days(7));

If we had a registration system, then that would work, but trying to fix IsLogFromCurrentProject seems futile.

**Comment by sergiud** [comment]
As I see it, an internal registration system is still a better solution than shifting the burden of managing log file paths onto users.

**Comment by mturnock** [comment]
OK, thanks.  I've closed this one, and opened a new one to do the registration system approach. https://github.com/google/glog/pull/1086

**Pull request closed without merging**
