### PR TITLE
Update automake config

### PR DESCRIPTION
**Pull request by aaronjwood**
This resolves a bit of an obscure issue for me. Here's what's happening:

I'm trying to compile a project from source that uses glog. This project needs to be compiled for ARM (aarch64) and the way I'm running this is inside of a container (Docker) on an x86 machine but that has binfmt_misc setup on the kernel to handle ARM binaries through `qemu-arm-static`. The container starts with a `scratch` image and just applies Ubuntu's core ARM64 image on top. In the end everything inside is emulated through qemu to mimic an isolated ARM environment.

When the project goes to build its version of glog it runs into:

```
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2007-07-22, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess
and
  http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2007-07-22

uname -m = aarch64
uname -r = 4.4.0-34-generic
uname -s = Linux
uname -v = #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016

/usr/bin/uname -p = 
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = 
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = aarch64
UNAME_RELEASE = 4.4.0-34-generic
UNAME_SYSTEM  = Linux
UNAME_VERSION = #53-Ubuntu SMP Wed Jul 27 16:06:39 UTC 2016
configure: error: cannot guess build type; you must specify one
```

Updating `config.guess` and `config.sub` from the latest versions here http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD and here http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD resolved the issue.

### CODE REVIEW

**Comment by aaronjwood** [comment]
This should be signed by Verizon Labs. If not, let me know and I will check back in with them.

**Comment by aaronjwood** [comment]
Has the CLA not been signed?

**Comment by aaronjwood** [comment]
I signed it!

**Comment by aaronjwood** [comment]
Any interest in merging this in?

**Comment by sergiud** [comment]
Obsoleted by #585.

**Pull request closed without merging**
