### PR TITLE
Update README to Bzlmod usage

### PR DESCRIPTION
**Pull request by Vertexwahn**
Update README to Bzlmod usage

### CODE REVIEW

**Comment by Vertexwahn** [comment]
@sergiud I forgot to update the documentation - this update the docs according to the change  https://github.com/google/glog/pull/1097

**Comment by sergiud** [comment]
Thanks! I intend to merge your changes after #1101, which heavily reworks the documentation. Sorry for the inconvenience.

**Comment by sergiud** [comment]
@Vertexwahn You can go ahead and apply your changes on top of the `mkdocs` branch.

**Review by sergiud — CHANGES_REQUESTED** [review]
The reworked documentation has been merged. Please rebase.

**Comment by sergiud** [comment]
Thank you!

**Review by sergiud — APPROVED** [review]

**Pull request merged**
