### PR TITLE
docs: move to mkdocs-material

### PR DESCRIPTION
**Pull request by sergiud**
localhost_8000_stable_
localhost_8000_0 7 1_logging_

### CODE REVIEW

**Comment by sergiud** [comment]
@drigz Could you please enable Github Pages deployment from the `gh-pages` branch (somewhere in project settings) and set the glog project URL to https://google.github.io/glog similar to [GoogleTest](https://github.com/google/googletest/deployments)?

**Comment by sergiud** [comment]
@drigz PTAL

**Comment by drigz** [comment]
Hey, sorry, just got back from vacation and it might take me a couple of days to catch up to this, let me know if you need me to just rubber stamp it without looking at the code.

**Comment by sergiud** [comment]
Thank you. No need to review. Just adjust the two settings:
1. Enable Github pages deployment from `gh-pages` branch.
    image
3. Set website to https://google.github.io/glog under "edit repository details"

**Comment by drigz** [comment]
image

image

Done, apologies for missing the first message!

**Comment by sergiud** [comment]
@drigz No worries. This works great now. Thank you!

**Pull request merged**
