### PR TITLE
Add signalhandler.cc in the vcproj of libglog static and libglog

### PR DESCRIPTION
**Pull request by hevy-CC4477**
This source file contains some function, present in headers but could be used because of linking error.

### CODE REVIEW

**Comment by hevy-CC4477** [comment]
I signed it!

**Comment by hevy-CC4477** [comment]
I signed it!

**Comment by hevy-CC4477** [comment]
I signed it!

**Comment by sergiud** [comment]
Closing as the changes are obsolete now.

**Pull request closed without merging**
