### PR TITLE
ci: reworked windows builds

### LINKED ISSUE #735: Two tests failed after successful compilation by msvc on the windows x64 platform
**Describe the bug**
When I used the code compiled by msbuild for unit testing, the test failed. The specific failure is as follows：

```
Test project F:/google/glog/build_amd64
      Start  1: demangle
 1/14 Test  #1: demangle .........................   Passed    0.04 sec
      Start  2: logging
 2/14 Test  #2: logging ..........................   Passed    0.48 sec
      Start  3: signalhandler
 3/14 Test  #3: signalhandler ....................   Passed    0.04 sec
      Start  4: stacktrace
 4/14 Test  #4: stacktrace .......................   Passed    0.03 sec
      Start  5: stl_logging
 5/14 Test  #5: stl_logging ......................   Passed    0.03 sec
      Start  6: symbolize
 6/14 Test  #6: symbolize ........................Exit code 0xc0000409
***Exception:   0.07 sec
F20211109 02:12:17.248965  6740 symbolize_unittest.cc:394] Check failed: symbol != NULL 
*** Check failure stack trace: ***
    @   00007FF614D964CB  public: void __cdecl google::LogMessage::Flush(void) __ptr64
    @   00007FF614D94AD9  public: __cdecl google::LogMessageFatal::~LogMessageFatal(void) __ptr64
    @   00007FF614D92771  (unknown)
    @   00007FF614D929BE  (unknown)
    @   00007FF614D9FF90  bool __cdecl google::glog_internal_namespace_::IsFailureSignalHandlerInstalled(void)
    @   00007FFAEB0784D4  BaseThreadInitThunk
    @   00007FFAEC3F1791  RtlUserThreadStart
      Start  7: cmake_package_config_init
 7/14 Test  #7: cmake_package_config_init ........   Passed    0.03 sec
      Start  8: cmake_package_config_generate
 8/14 Test  #8: cmake_package_config_generate ....   Passed    2.74 sec
      Start  9: cmake_package_config_build
 9/14 Test  #9: cmake_package_config_build .......***Failed    1.89 sec
Microsoft (R) Build Engine version 16.11.1+3e40a09f8 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
  Checking Build System
  Building Custom Rule F:/google/glog/src/package_config_unittest/working_config/CMakeLists.txt
  glog_package_config.cc
LINK : fatal error LNK1104: cannot open file 'F:\google\glog\build_amd64\Debug\glogd.lib' [F:\google\glog\build_amd64\test_package_config\working_config\glog_package_config.vcxproj]
      Start 10: cmake_package_config_cleanup
10/14 Test #10: cmake_package_config_cleanup .....   Passed    0.03 sec
      Start 11: cleanup_init
11/14 Test #11: cleanup_init .....................   Passed    0.02 sec
      Start 13: cleanup_immediately
12/14 Test #13: cleanup_immediately ..............   Passed    3.19 sec
      Start 14: cleanup_with_prefix
13/14 Test #14: cleanup_with_prefix ..............   Passed    3.19 sec
      Start 12: cleanup_logdir
14/14 Test #12: cleanup_logdir ...................   Passed    0.02 sec
86% tests passed, 2 tests failed out of 14
Total Test time (real) =  11.81 sec
The following tests FAILED:
	  6 - symbolize (Exit code 0xc0000409
)
	  9 - cmake_package_config_build (Failed)
```

**To Reproduce**
```
1. git clone https://github.com/google/glog
2. git -C "F:\google\glog" rev-parse --git-dir
   git -C "F:\google\glog" clean -xdf
   git -C "F:\google\glog" fetch --recurse-submodules=no --force
   git -C "F:\google\glog" reset --hard 3369666
   git -C "F:\google\glog" remote prune origin
3. set VSCMD_SKIP_SENDTELEMETRY=1 & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=amd64
4. cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DCMAKE_BUILD_TYPE=Release ..
5. msbuild /m /p:Platform=x64 /p:Configuration=Release glog.sln /t:Rebuild /p:BuildInParallel=true
6. ctest --build-config Release --output-on-failure
```

**Expected behavior**
All test pass.

**Observed Behavior**
Unit test failed.

**Environm**ent
OS: Windows Server 2016 1607
CPU: AMD EPYC 7452 32-Core Processor
Compiler: MSVC 14.29.30133
Language: ENU

### PR DESCRIPTION
**Pull request by sergiud**
Closes #735

### CODE REVIEW

**Comment by sergiud** [comment]
@drigz I've been trying to fix merging of multiple coverage reports (mainly MinGW and Linux) over the the past weeks. However, this turned out to be very tricky due to the way both Coveralls and Github workflows work. Since the Github workflows are defined in separate files, merging the reports cannot be done automatically and requires additional logic which is not straightforward to implement. Additionally, Coveralls seems to have problems parsing MinGW coverage reports (a 0% coverage is always reported).

At this point, I believe switching to Codecov is a better solution in the long-term.

**Comment by drigz** [comment]
LGTM. Let me know if you need any action from me to enable Codecov.

**Comment by sergiud** [comment]
Thanks. We would need  a `CODECOV_TOKEN` secret with Codecov token assigned to it as detailed [here](https://docs.codecov.com/docs#basic-usage). Coveralls bot access to repo can be revoked.

**Comment by drigz** [comment]
Where would we store the CODECOV_TOKEN? Assuming we wouldn't be manually uploading coverage data, it's not clear how it should be used. It also says "Note: Token not required for public repositories uploading from Travis, CircleCI, AppVeyor, Azure Pipelines or GitHub Actions." - does this apply to us?

**Comment by sergiud** [comment]
I obviously ignored that note, thanks. The token does not seem to be necessary.

**Pull request merged**
