### PR TITLE
[TEST] ci: support visual studio 2019

### PR DESCRIPTION
**Pull request by sergiud**

### CODE REVIEW

**Comment by sergiud** [comment]
@NeroBurner Glog AppVeyor builds stopped working 6 months ago. Do you happen to know what could be the problem? According to @drigz, AppVeyor is correctly authorized in project settings.

**Comment by NeroBurner** [comment]
just for VS2019 or all of AppVeyor? The `master` builds seem to be working (all green), and `.appveyor.yml` latest change is by me from may 2018

**Comment by sergiud** [comment]
AppVeyor is completely  missing  in merge checks meaning all environments are affected. According to [this page](https://ci.appveyor.com/project/google-admin/glog), glog was last build 6 months ago. Any ideas?

**Comment by NeroBurner** [comment]
unfortunately no, haven't touched appveyor builds for a long time

Maybe a move to GitHub Actions would be an improvement, as glog is hosted primarily on GitHub :thinking:

**Pull request closed without merging**
