### PR TITLE
added absolute cmake path to sources

### PR DESCRIPTION
**Pull request by nidegen**
I added the CMake List file path as prefix to the included files so it works when configured as subproject!:)

### CODE REVIEW

**Comment by nidegen** [comment]
i signed it!

**Comment by sergiud** [comment]
Why is this needed? Glog can already be included using `add_subdirectory` as is.

**Comment by nidegen** [comment]
ok, makes sense. i was adding it with 'include'. probably the wrong way:)

**Comment by nidegen** [comment]
@sergiud actually, `add_subdirectory` only works when it actually is a subdirectory. in my case, it is not, hence it would come in handy...

i am trying to include it in an iOS target. maybe there is an easier way to build and link it to an iOS project?

**Comment by nidegen** [comment]
as i deleted the branch already, i will open another PR

**Comment by sergiud** [comment]
I cannot follow what you are doing. Can you elaborate? Why doesn't ` add_subdirectory` work? What's the error? Can you provide the CMake output?

**Comment by nidegen** [comment]
it was
`
CMake Error at /Users/nidegen/Developer/OpenMapper/OpenMapper/CMakeLists.txt:59 (ADD_SUBDIRECTOR
Y):
  add_subdirectory not given a binary directory but the given source
  directory "/Users/nidegen/Developer/OpenMapper/OpenMapper/thirdparty/glog"
  is not a subdirectory of
  "/Users/nidegen/Developer/OpenMapper/OpenMapper/wrapper/ios".  When
  specifying an out-of-tree source a binary directory must be explicitly
  specified.
`
i guess i can add the binary dir. i am doing this as a side project, should look more carefully:)

**Comment by nidegen** [comment]
however, it completely messes up the build folder structure that way..

**Comment by nidegen** [comment]
the absolute paths would def make life easier

**Pull request closed without merging**
