### PR TITLE
symbolize_unittest: make it a bit more portable

### PR DESCRIPTION
**Pull request by vapier**

### CODE REVIEW

**Comment by vapier** [comment]
rebase of #87

**Comment by sergiud** [comment]
Thanks for the PR.

Could you please rebase and push the commit again as I no longer seem to have access to your branch after force pushing.

**Comment by vapier** [comment]
pretty sure you can fetch the commit you clobbered from the remote

```
$ git fetch https://github.com/vapier/glog 233df366d56df9d3d32898451f2ba1ace7e234de
$ git cherry-pick FETCH_HEAD
```

**Comment by sergiud** [comment]
That's not the issue. I simply can't push to your `master` since the branch no longer contains the PR commit.

For future reference, please submit your changes from a dedicated feature branch to avoid confusion that local and remote branches with the same name can cause.

**Comment by vapier** [comment]
yeah, that's not really a thing.  don't force push if you don't want to clobber/rewrite a ref.

i can rebase the original commit onto the latest branch & push to my repo again.  but i can't re-open PR's in this project.  i can only file new ones.

**Comment by sergiud** [comment]
> yeah, that's not really a thing. don't force push if you don't want to clobber/rewrite a ref.

What is not a thing? Force pushing is perfectly fine and necessary when rebasing which is what I did. I simply messed the local ref when pushing.

This works know. Thanks.

**Comment by vapier** [comment]
requiring people use non-default branches to generate PRs to somehow protect against bad force pushes.  you force pushed the wrong state to a remote branch.  giving it a diff name wouldn't have helped -- you would have typed the remote branch in order to rewrite it.

but whatever, let's just agree to disagree and move on.

**Comment by sergiud** [comment]
That's fine. I'm eager to learn.

> giving it a diff name wouldn't have helped

Why not? Compare
```bash
git push git@github.com:vapier/glog.git master:master # whoops
```
vs
```bash
git push git@github.com:vapier/glog.git portable-labels
```
If you have a better suggestion how to avoid such a mishap, please let me know.

**Pull request merged**
